@startuml AutohausReadService

skinparam classAttributeIconSize 0

package java.util {
    interface List<T>
    interface Map<K, V>
    class UUID
}

package org.springframework {
    package stereotype {
        interface Service
    }

    package transaction.annotation {
        interface Transactional
    }
}

package com.acme.autohaus {
    package entity {
        class Autohaus << entity >>

        Autohaus .up[hidden].> UUID
        Autohaus .up[hidden].> Service
        Autohaus .up[hidden].> Transactional
    }

    package repository {
        interface AutohausRepository << control >>
    }

    package service #DDDDDD {
        class AutohausReadService << control >> << @Service >> {
            + findById(id: UUID, boolean: fetchAutos): Autohaus
            + find(suchkriterien: Map<String, List<String>>): List<Autohaus>
        }

        AutohausReadService o--> "1" AutohausRepository : repo
        AutohausReadService .up.> Autohaus
        AutohausReadService .up.> UUID
        AutohausReadService .up.> List
        AutohausReadService .up.> Map
        AutohausReadService .up.> Service
        AutohausReadService ..> Transactional
    }
}

hide empty members

footer (c) Jonas Kirschner

@enduml
