@startuml AutohausReadService

skinparam classAttributeIconSize 0

package org.springframework.stereotype {
    interface Service
}

package java.util {
    interface List<T>
    interface Map<K,V>
}

package com.acme.autohaus {
    package entity {
        class Autohaus << entity >>

        Autohaus .up[hidden].> List
    }

    package repository {
        class AutohausRepository << control >> << @Repository >>
    }

    package service #DDDDDD {
        class AutohausReadService << control >> << @Service >> {
            + get(queryParams: Map<String,List<String>>): List<Autohaus>
            + getById(id: String): Autohaus
        }

        AutohausReadService o--> AutohausRepository : repo
        AutohausReadService .right.> Autohaus
        AutohausReadService .up> Service
        AutohausReadService .up> List
        AutohausReadService .up.> Map
    }
}

hide empty members

footer (c) Jonas Kirschner

@enduml
